Update ios.yml

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -95,10 +95,10 @@ jobs:
           APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
           MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} # Secret for match repo password
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-          XCODE_VERSION: 16.2
+          #XCODE_VERSION: 16.2
 
-      - name: 🪵 Dump Full Xcode Gym Log
-        if: failure()
-        run: |
-          echo "🔍 Checking for Fastlane gym build log..."
-          cat ~/Library/Logs/gym/Runner-Runner.log || echo "No log found."
+      #- name: 🪵 Dump Full Xcode Gym Log
+      # if: failure()
+      #run: |
+      # echo "🔍 Checking for Fastlane gym build log..."
+      #cat ~/Library/Logs/gym/Runner-Runner.log || echo "No log found."
